version: "3.3"
services:
  app:
    build: .
    volumes:
      - .:/home/app/docs
      - /home/app/docs/node_modules/
    command: yarn run docker
    ports:
      - "4000:4000"
      - "3001:3001"
