const gulp        = require('gulp');
const gutil       = require('gulp-util');
const sass        = require('gulp-sass');
const sourcemaps  = require('gulp-sourcemaps');
const minify      = require('gulp-minify');

const fs          = require('fs');
const spawn       = require('child_process').spawn;

const browserSync = require('browser-sync').create();
const _           = require('lodash');
const del         = require('del');
const runSequence = require('run-sequence');
const shell       = require('shelljs');

const buildDate     = new Date().toISOString().replace(/T/, ' ').replace(/\..+/, '');
const PORT          = 3000;
const DIST_FOLDER   = '_site';            // DO NOT CHANGE THIS, IS USED BY TRAVIS FOR DEPLOYMENT IN MANIFEST
const CONFIG        = '_config.yml';
const CONFIG_TEST   = '_config_test.yml';

/* DONT EDIT BELOW */
gutil.log(`Gulp started at ${buildDate}`);

const paths = {
  styles: {
    src: '_assets/styles/**/*.scss',
    dest: `${DIST_FOLDER}/public/styles`
  },
  images: {
    src: '_assets/images/**/*',
    dest: `${DIST_FOLDER}/public/images`
  },
  scripts: {
    src: '_assets/js/**/*.js',
    dest: `${DIST_FOLDER}/public/js`
  }
}

/*************************************************
  FUNCTIONS
**************************************************/
const throwErr = (plugin, error) => {
  throw new gutil.PluginError({
    plugin: plugin,
    message: error
  }, { showStack: true });
}

const spawnJekyll = (test, watch, cb) => {
  const jekyll_indicator = gutil.colors.cyan("[JEKYLL]");
  const doneStr = 'done in';
  const child = spawn('bundle', [
    'exec',
    'jekyll',
    'build',
    '--config',
    (test ? CONFIG_TEST : CONFIG),
    (watch ? '-w' : '')
  ], { cwd: process.cwd()});

  child.stdout.setEncoding('utf8');
  child.stderr.setEncoding('utf8');

  child.stdout.on('data', data => {
      _.each(data.split('\n'), line => {
        if (line) {
          gutil.log(jekyll_indicator, line);
          if (line.indexOf(doneStr) !== -1 && watch) {
            browserSync.reload();         // Rebuild was triggered by Hugo, so we'll reload the page
          }
        }
      });
  });

  child.stderr.on('data', data => {
      _.each(data.split('\n'), line => {
        if (line) {
          gutil.log(jekyll_indicator, gutil.colors.red(line));
        }
      });
      gutil.beep();
  });

  child.on('close', function(code) {
      gutil.log(jekyll_indicator, "Closed with exit code", code);
      if (cb && _.isFunction(cb)) {
        cb(code);
      }
  });
};

const build = (t, cb) => {
  spawnJekyll(t, false, (code) => {
    if (code !== 0) {
      throwErr('jekyll:build', `Jekyll exit code is ${code}, check your Jekyll setup`);
    } else {
      cb();
    }
  });
};

const escapeMapping = str => {
  return str.replace(/\//g, '\\\/')
      .replace(/\+/g,'\\\+')
      .replace(/\./g,'\\.')
      .replace(/\(/g,'\\(')
      .replace(/\)/g,'\\)')
      .replace(/\'/g,'\\\'')
      .replace(/ /g,'\\ ')
      .replace(/\:/g,'\\\:')
      .replace(/\"/g,'\\\"');
}

const mappings = (write, cb) => {
  fs.readFile('_assets/mappings/redirect.json', (err, data) => {
    if (err) {
      throwErr('write:mappings', `Cannot read _assets/mappings/redirect.json`);
    }
    let mappings = null;
    try {
      mappings = JSON.parse(data);
    } catch (e) {
      throwErr('write:mappings', `Cannot read _assets/mappings/redirect.json: ${e}`);
    }
    if (mappings.redirect) {
      const red = mappings.redirect;
      let mappingsArr = [
            '####################################################################################',
            `# Mendix redirect mapping, generated on ${buildDate}`,
            '# Do not change this file, it is generated by Gulp using \'gulp write:mappings\'',
            '####################################################################################',
            ''
          ],
          done = [];
      _.forEach(red, r => {
        if (!r.to || !r.from) {
          throwErr('write:mappings', `Error reading _assets/mappings/redirect.json, this is not a correct mapping: ${JSON.stringify(r, null, 4)}`);
        }
        const to = r.to.trim(),
              from = r.from.trim(),
              lastChar = to.substr(-1),
              mdFile = '.' + to + (lastChar === '/' ? 'index.md' : '.md'),
              htmlFile = gutil.replaceExtension(mdFile, '.html'),
              hash = new Buffer(`${from}-${to}`).toString('base64'),
              caseSensitive = to.toLowerCase() === from.toLowerCase();

        if (!shell.test('-e', mdFile) && !shell.test('-e', htmlFile)) {
          throwErr('write:mappings', `Error in mappings. There is no file for the mapping in mappings.json to: ${gutil.colors.cyan(to)}`);
        } else if (to === from) {
          throwErr('write:mappings', `Error in mappings. ${gutil.colors.cyan(to)} is the same as ${gutil.colors.cyan(from)}`);
        } else if (done.indexOf(hash) !== -1) {
          throwErr('write:mappings', `You have a duplicate mapping for. ${gutil.colors.cyan(from)} => ${gutil.colors.cyan(to)}`);
        }
        let mappingStr = '',
            fromStr = from.substr(-1) === '/' ? from + '?' : from + '/?';

        mappingsArr.push((caseSensitive ? '~' : '~*') + `${escapeMapping(fromStr)} ${to};`);
      });
      const mappingsFile = mappingsArr.join('\n');

      if (write) {
        fs.writeFile('_site/mappings/redirect.map', mappingsFile, err => {
          if (err) {
            throwErr('write:mappings', `Error writing _site/mappings/redirect.map: ${err}`);
          } else {
            gutil.log('Mappings written to _site/mappings/redirect.map');
          }
          cb();
        })
      } else {
        cb();
      }
    } else {
      throwErr('write:mappings', `No redirects found in mappings.json`);
    }
  });
};
/*************************************************
  TASKS
**************************************************/

gulp.task('clean', () => {
  return del([
    DIST_FOLDER
  ], { force: true });
});

gulp.task('write:mappings', done => {
  mappings(true, done);
});

gulp.task('copy:images', () => {
  return gulp
    .src(paths.images.src)
    .pipe(gulp.dest(paths.images.dest));
});

gulp.task('compress:js', () => {
  return gulp
    .src(paths.scripts.src)
    .pipe(minify({
      ext: {
        src: '-debug.js',
        min: '.js'
      }
    }))
    .pipe(gulp.dest(paths.scripts.dest));
});

gulp.task('sass:build', () => {
  return gulp
    .src(paths.styles.src)
    .pipe(sass({
      outputStyle: 'compressed'
    }).on('error', sass.logError))
    .pipe(gulp.dest(paths.styles.dest))
});

gulp.task('sass:dev', () => {
  return gulp
    .src(paths.styles.src)
    .pipe(sourcemaps.init())
    .pipe(sass({
      outputStyle: 'compressed'
    }).on('error', sass.logError))
    .pipe(sourcemaps.write())
    .pipe(gulp.dest(paths.styles.dest))
    .pipe(browserSync.stream());
});

gulp.task('jekyll:build', [], done => {
  build(false, done);
});

gulp.task('jekyll:build-test', [], done => {
  build(true, done);
});

gulp.task('dev', ['sass:dev', 'copy:images', 'compress:js'], done => {
  browserSync.init({
      port: PORT,
      serveStatic: [ DIST_FOLDER ],
      serveStaticOptions: {
          extensions: ['html'] // pretty urls (so this works locally as it would online)
      }
  });
  spawnJekyll(true, true);
  gulp.watch(paths.styles.src, ['sass:dev']);
  gulp.watch(paths.scripts.src, ['compress:js']);
  gulp.watch(paths.images.src, ['copy:images']);
});

gulp.task('serve', done => {
  runSequence('clean', 'dev');
})

gulp.task('build', done => {
  runSequence('clean', ['jekyll:build', 'sass:build', 'copy:images', 'compress:js', 'write:mappings'], done);
});

gulp.task('build-test', done => {
  runSequence('clean', ['jekyll:build-test', 'sass:build', 'copy:images', 'compress:js', 'write:mappings'], done);
});
