openapi: 3.0.1
info:
  title: "Catalog Registration API"
  description: "This is the Registration API specification. You can use it to register and manage your data sources and datasets in the Catalog."
  termsOfService: "#"
  contact:
    email: PlatformCore@mendix.com
  version: "5.1.0"
servers:
  - url: "https://catalog.mendix.com/rest/registration/v5"
paths:
  /applications:
    post:
      tags:
        - Applications
      summary: "Registers an application"
      security:
        - OAuth2:
            [
              "mx:datahub:services:write",
              "openid",
              "offline_access",
              "mx:user:profile:v1:read"
            ]
        - PersonalAccessTokens: []
    get:
      tags:
        - Applications
      summary: "Retrieves all the applications from users company"
      security:
        - OAuth2:
            [
              "mx:datahub:services:read",
              "openid",
              "offline_access",
              "mx:user:profile:v1:read"
            ]
        - PersonalAccessTokens: []
  /applications/{AppUUID}:
    get:
      tags:
        - Applications
      summary: "Retrieves the details of a particular application"
      security:
        - OAuth2:
            [
              "mx:datahub:services:read",
              "openid",
              "offline_access",
              "mx:user:profile:v1:read"
            ]
        - PersonalAccessTokens: []
    delete:
      tags:
        - Applications
      summary: "Deletes the specified application and all environments and endpoints associated to it"
      description: "Deleting an application can only be done by the owner of the resource’s application, company admins, or Catalog curators."
      security:
        - OAuth2:
            [
              "mx:datahub:services:write",
              "openid",
              "offline_access",
              "mx:user:profile:v1:read"
            ]
        - PersonalAccessTokens: []
    put:
      tags:
        - Applications
      summary: "Register a new application or update an existing application at the given UUID. Currently registered application are overwritten with the values provided in this request body."
      description: "Some PUT operations can only be done by the owner of the resource’s application, company admins, or Catalog curators."
      security:
        - OAuth2:
            [
              "mx:datahub:services:write",
              "openid",
              "offline_access",
              "mx:user:profile:v1:read"
            ]
        - PersonalAccessTokens: []
  /applications/{AppUUID}/environments:
    post:
      tags:
        - Environments
      summary: "Registers an environment for the specified application"
      security:
        - OAuth2:
            [
              "mx:datahub:services:write",
              "openid",
              "offline_access",
              "mx:user:profile:v1:read"
            ]
        - PersonalAccessTokens: []
    get:
      tags:
        - Environments
      summary: "Retrieves the details of all environments of an application"
      security:
        - OAuth2:
            [
              "mx:datahub:services:read",
              "openid",
              "offline_access",
              "mx:user:profile:v1:read"
            ]
        - PersonalAccessTokens: []
  /applications/{AppUUID}/environments/{EnvironmentUUID}:
    get:
      tags:
        - Environments
      summary: "Retrieves the details of a particular environment of an application"
      security:
        - OAuth2:
            [
              "mx:datahub:services:read",
              "openid",
              "offline_access",
              "mx:user:profile:v1:read"
            ]
        - PersonalAccessTokens: []
    delete:
      tags:
        - Environments
      summary: "Deletes the specified environment"
      description: "Deleting an environment can only be done by the owner of the resource’s application, company admins, or Catalog curators."
      security:
        - OAuth2:
            [
              "mx:datahub:services:write",
              "openid",
              "offline_access",
              "mx:user:profile:v1:read"
            ]
        - PersonalAccessTokens: []
    put:
      tags:
        - Environments
      summary: "Registers or updates a specific environment at the given UUID. Currently registered environments are overwritten with the values provided in this request body."
      description: "Some PUT operations can only be done by the owner of the resource’s application, company admins, or Catalog curators."
      security:
        - OAuth2:
            [
              "mx:datahub:services:write",
              "openid",
              "offline_access",
              "mx:user:profile:v1:read"
            ]
        - PersonalAccessTokens: []
  /applications/{AppUUID}/environments/{EnvironmentUUID}/published-endpoints:
    put:
      tags:
        - Endpoints
      summary: "Registers all published endpoints for the specified app UUID and environment UUID. Currently registered published endpoints are overwritten with the values provided in this request body. Endpoints that are not in the new request will be deleted."
      description: "Some PUT operations can only be done by the owner of the resource’s application, company admins, or Catalog curators."
      security:
        - OAuth2:
            [
              "mx:datahub:services:write",
              "openid",
              "offline_access",
              "mx:user:profile:v1:read"
            ]
        - PersonalAccessTokens: []
    post:
      tags:
        - Endpoints
      summary: "Registers a published endpoint for the specified app and environment."
      security:
        - OAuth2:
            [
              "mx:datahub:services:write",
              "openid",
              "offline_access",
              "mx:user:profile:v1:read"
            ]
        - PersonalAccessTokens: []
    get:
      tags:
        - Endpoints
      summary: "Returns all published endpoints for the specified environment."
      security:
        - OAuth2:
            [
              "mx:datahub:services:read",
              "openid",
              "offline_access",
              "mx:user:profile:v1:read"
            ]
        - PersonalAccessTokens: []
  ? /applications/{AppUUID}/environments/{EnvironmentUUID}/published-endpoints/{EndpointUUID}
  : get:
      tags:
        - Endpoints
      summary: "Returns details of the specified published endpoint"
      security:
        - OAuth2:
            [
              "mx:datahub:services:read",
              "openid",
              "offline_access",
              "mx:user:profile:v1:read"
            ]
        - PersonalAccessTokens: []
    delete:
      tags:
        - Endpoints
      summary: "Deletes the specified published endpoint"
      description: "Deleting an endpoint can only be done by the owner of the resource’s application, company admins, or Catalog curators."
      security:
        - OAuth2:
            [
              "mx:datahub:services:write",
              "openid",
              "offline_access",
              "mx:user:profile:v1:read"
            ]
        - PersonalAccessTokens: []
    put:
      tags:
        - Endpoints
      summary: "Updates the details of the specified published endpoint. Will create the published endpoint if it does not exist yet."
      description: "Some PUT operations can only be done by the owner of the resource’s application, company admins, or Catalog curators."
      security:
        - OAuth2:
            [
              "mx:datahub:services:write",
              "openid",
              "offline_access",
              "mx:user:profile:v1:read"
            ]
        - PersonalAccessTokens: []
  /applications/{AppUUID}/environments/{EnvironmentUUID}/consumed-endpoints:
    put:
      tags:
        - Endpoints
      summary: "Registers all consumed endpoints for the specified app and environment. Currently registered consumed endpoints are overwritten with the values provided in this request body."
      description: "Some PUT operations can only be done by the owner of the resource’s application, company admins, or Catalog curators."
      security:
        - OAuth2:
            [
              "mx:datahub:services:write",
              "openid",
              "offline_access",
              "mx:user:profile:v1:read"
            ]
        - PersonalAccessTokens: []
    get:
      tags:
        - Endpoints
      summary: "Returns all consumed endpoints for the specified environment."
      security:
        - OAuth2:
            [
              "mx:datahub:services:read",
              "openid",
              "offline_access",
              "mx:user:profile:v1:read"
            ]
        - PersonalAccessTokens: []
  ? /applications/{AppUUID}/environments/{EnvironmentUUID}/consumed-endpoints/{EndpointUUID}
  : get:
      tags:
        - Endpoints
      summary: "Return details of specified consumed endpoint"
      security:
        - OAuth2:
            [
              "mx:datahub:services:read",
              "openid",
              "offline_access",
              "mx:user:profile:v1:read"
            ]
        - PersonalAccessTokens: []
  /transform/dependenciesjson:
    post:
      tags:
        - Endpoints
      summary: "Transforms contents of the dependencies.json file for your Mendix app into request bodies for the PUT published/consumed-endpoints operations of this API"
      description: 'For this call the contents of the dependencies.json file have to be included. <br> The dependencies.json file for your Mendix app is usually located in your project folder in the deployment\model directory. <br> Contents of this file must be included in escaped JSON format.'
      security:
        - OAuth2:
            [
              "mx:datahub:services:read",
              "openid",
              "offline_access",
              "mx:user:profile:v1:read"
            ]
        - PersonalAccessTokens: []
components:
  securitySchemes:
    OAuth2:
      $ref: "catalog-common-definitions_v5.yaml#/components/securitySchemes/OAuth2"
    PersonalAccessTokens:
      $ref: "catalog-common-definitions_v5.yaml#/components/securitySchemes/PersonalAccessTokens"
