#!/bin/bash

set -ev

#
# Can we set up something (travis cache?) to ensure that this change doesn't have to be made manually.
# Can always leave the switch at MAKEREDIRECT="true" but this will slow down deployment unnecessarily.
# Currently have to rely on writers making the change manually after the change is successful
#

#########################################################################################################
#                                                                                                       #
# Set MAKEREDIRECT to "true" when you make changes to any redirects                                     #
# Set MAKEREDIRECT to "false" once redirects have been pushed to development AND master                 #
#                                                                                                       #
#########################################################################################################

MAKEREDIRECT="true"

echo "HOME is $HOME"
echo "TRAVIS_BUILD_DIR is $TRAVIS_BUILD_DIR"
echo "Target AWS bucket is $TARGETAWSBUCKET"

objectredirect () {
#  echo "We will make a local file at $TRAVIS_BUILD_DIR/_site/$1"
#  put an old date on it to stop it being uploaded with sync
  mkdir -pv $(dirname $TRAVIS_BUILD_DIR/_site/$1)
  touch -t 202001010001 $TRAVIS_BUILD_DIR/_site/$1
  if ([ "${MAKEREDIRECT}" == "true" ])
  # Only make the redirects if if MAKEDIRECT is "true" as it takes about 10 minutes and isn't needed if the redirects file hasn't changed
  then
    aws s3api put-object --bucket $TARGETAWSBUCKET --key $1 --content-type text/html --website-redirect-location $2
  fi
}

#########################################################################################################
#                                                                                                       #
# Set up a redirect using objectredirect '{original}' '{redirect to}'                                   #
# Remember to set MAKEREDIRECT to "true" until redirects have been pushed to development AND master     #
#                                                                                                       #
#########################################################################################################

#	/****************************************************
#     * PERMANENT REDIRECTS FOR DOCUMENTS
#     ****************************************************/
#	 /****************************************************
#     * Documentation Site (permanent, unmapped) 
#     ****************************************************/
objectredirect 'docs/Overview' '/'
objectredirect 'docs/index' '/'
#	/****************************************************
#     * Studio Pro Guide (permanent, mapped)
#     ****************************************************/
objectredirect 'refguide/mindsphere/mindsphere-module-details' '/partners/siemens/mindsphere-module-details'
objectredirect 'refguide/customizing-phonegap-build-packages' '/howto/mobile/customizing-phonegap-build-packages'
#	/****************************************************
#     * Reference Guide version 7 (permanent, unmapped)
#     ****************************************************/	
objectredirect 'refguide/moving-from-6-to-7' '/refguide7/moving-from-6-to-7'
#	/****************************************************
#     * How-to's (permanent, unmapped)
#     ****************************************************/
objectredirect 'howtogeneral/bestpractices/ux-best-practices' '/howto/front-end/ux-best-practices'
objectredirect 'howtogeneral/bestpractices/best-practices-security-and-improvements-for-mendix-applications' '/howto/security/best-practices-security'
objectredirect 'howtogeneral/bestpractices/best-practices-for-app-performance-in-mendix-7' '/howto/general/community-best-practices-for-app-performance'
objectredirect 'howto/ux/configuring-your-theme' '/howto/front-end/configuring-your-theme'
#	/****************************************************
#     * How-to's version 7 (permanent, unmapped)
#     ****************************************************/	
objectredirect 'howto7/ux/configuring-your-theme' '/howto7/front-end/configuring-your-theme'
#	/****************************************************
#     * Studio Guide (permanent, unmapped)
#     ****************************************************/
objectredirect 'howto/tutorials/index' '/studio/general'
objectredirect 'howto/tutorials/mendix-tutorials' '/studio/general'
#	/****************************************************
#     * Developer Portal Guide (permanent, unmapped) 
#     ****************************************************/
objectredirect 'howtogeneral/mendixcloud/trends' '/developerportal/operate/trends'
objectredirect 'developerportal/operate/mendix-cloud-status' '/developerportal/deploy/mendix-cloud-status'
objectredirect 'community/tools/the-mendix-job-board' '/developerportal/community-tools/mendix-job-board'
objectredirect 'community/tools/the-mendix-mvp-program' '/developerportal/community-tools/mendix-mvp-program'
objectredirect 'mendixcloud/deploying-to-the-cloud' '/developerportal/deploy/mendix-cloud-deploy'
objectredirect 'mendixcloud/maintenance-windows' '/developerportal/deploy/maintenance-windows'
objectredirect 'developerportal/howto/migrating-to-v4' '/developerportal/deploy/migrating-to-v4'
objectredirect 'deployment/mendixcloud/how-to-deploy-a-mendix-app-on-azure' '/developerportal/deploy/azure-deploy'
objectredirect 'mendixcloud/how-to-link-app-to-node' '/developerportal/deploy/licensing-apps'
objectredirect 'howtogeneral/support/index' '/developerportal/support/'
objectredirect 'deployment/mendixcloud/sending-email' '/developerportal/deploy/sending-email'
objectredirect 'howto/deploying-a-mendix-app-to-cloud-foundry' '/developerportal/deploy/cloud-foundry-deploy'
#	/****************************************************
#     * App Store Guide (permanent, mapped & unmapped) 
#     ****************************************************/	
objectredirect 'community/app-store/app-store-overview' '/appstore/general/app-store-overview'
objectredirect 'community/app-store/index' '/appstore/index'
objectredirect 'developerportal/app-store/app-store-content' '/appstore/general/app-store-content'
objectredirect 'developerportal/app-store/app-store-content-support' '/appstore/general/app-store-content-support'
objectredirect 'developerportal/app-store/app-store-overview' '/appstore/general/app-store-overview'
objectredirect 'developerportal/app-store/share-app-store-content' '/appstore/general/share-app-store-content'
#    /****************************************************
#     * Add-on Guides (permanent, mapped)
#     ****************************************************/
objectredirect 'addons/apm-addon/index' '/addons/apd-addon/'
objectredirect 'apm/installation-guide' '/addons/apd-addon/ig-two'
objectredirect 'apm/reference-guide/rg-2/reference-guide-2' '/addons/apd-addon/rg-two-apm'
#	/****************************************************
#     * PERMANENT REDIRECTS FROM PRODUCTS
#     ****************************************************/	
#	/****************************************************
#     * From Studio Pro version 8 (permanent, mapped)
#     ****************************************************/
objectredirect 'refguide/modeler' '/refguide/modeling'
objectredirect 'refguide/Modeler' '/refguide/modeling'
objectredirect 'refguide/desktop-modeler' '/refguide/modeling'
objectredirect 'refguide/desktop-modeler-overview' '/refguide/studio-pro-overview'
objectredirect 'refguide/download-from-team-server-dialog' '/refguide/download-from-version-control-dialog'
objectredirect 'refguide/open-project-dialog' '/refguide/open-app-dialog'
objectredirect 'refguide/upload-to-team-server-dialog' '/refguide/upload-to-version-control-dialog'
objectredirect 'refguide/microflow-expressions' '/refguide/expressions'
objectredirect 'deployment/cloud-foundry/index' '/developerportal/deploy/cloud-foundry-deploy'
objectredirect 'howto/solving-load-and-import-errors' '/howto/monitoring-troubleshooting/solving-load-and-import-errors'
objectredirect 'refguide/drop-down-widget' '/refguide/drop-down'
objectredirect 'refguide/horizontal-split-pane' '/refguide/scroll-container'
objectredirect 'refguide/vertical-split-pane' '/refguide/scroll-container'
objectredirect 'refguide/Select++Elements' '/refguide/select--elements'
objectredirect 'refguide/Developing+Hybrid+Mobile+Apps' '/refguide/developing-hybrid-mobile-apps'
objectredirect 'refguide/enumeration-values' '/refguide/enumerations'
objectredirect 'refguide/inheritance-split' '/refguide/object-type-decision'
objectredirect 'refguide/exclusive-split' '/refguide/decision'
objectredirect 'refguide/menu-item' '/refguide/menu'
objectredirect 'refguide/Show+Page' '/refguide/show-page'
objectredirect 'refguide/Validation+Feedback' '/refguide/validation-feedback'
objectredirect 'refguide/Show+Message' '/refguide/show-message'
objectredirect 'refguide/Show+Home+Page' '/refguide/show-home-page'
objectredirect 'refguide/Download+File' '/refguide/download-file'
objectredirect 'refguide/Close+Form' '/refguide/close-page'
objectredirect 'refguide/Row+(document+template)' '/refguide/row-document-template'
objectredirect 'refguide/row-(document-template)' '/refguide/row-document-template'
objectredirect 'refguide/Table+(document+template' '/refguide/table-document-template'
objectredirect 'refguide/table-(document-template)' '/refguide/table-document-template'
objectredirect 'refguide/Cell+(document+template)' '/refguide/cell-document-template'
objectredirect 'refguide/cell-(document-template)' '/refguide/cell-document-template'
objectredirect 'refguide/Static+Image+(document+template)' '/refguide/static-image-document-template'
objectredirect 'refguide/static-image-(document-template)' '/refguide/static-image-document-template'
objectredirect 'refguide/Title+(document+template)' '/refguide/title-document-template'
objectredirect 'refguide/title-(document-template)' '/refguide/title-document-template'
objectredirect 'refguide/Static+label+(document+template)' '/refguide/static-label-document-template'
objectredirect 'refguide/static-label-(document-template)' '/refguide/static-label-document-template'
objectredirect 'refguide/Page+Break+(document+template)' '/refguide/page-break-document-template'
objectredirect 'refguide/page-break-(document-template)' '/refguide/page-break-document-template'
objectredirect 'refguide/Line+Break+(document+template)' '/refguide/line-break-document-template'
objectredirect 'refguide/line-break-(document-template)' '/refguide/line-break-document-template'
objectredirect 'refguide/Header+(document+template)' '/refguide/header-document-template'
objectredirect 'refguide/header-(document-template)' '/refguide/header-document-template'
objectredirect 'refguide/Footer+(document+template)' '/refguide/footer-document-template'
objectredirect 'refguide/footer-(document-template)' '/refguide/footer-document-template'
objectredirect 'refguide/Dynamic+label+(document+template)' '/refguide/dynamic-label-document-template'
objectredirect 'refguide/dynamic-label-(document-template)' '/refguide/dynamic-label-document-template'
objectredirect 'refguide/Template+Grid+(document+template)' '/refguide/template-grid-document-template'
objectredirect 'refguide/template-grid-(document-template)' '/refguide/template-grid-document-template'
objectredirect 'refguide/Data+Grid+(document+template)' '/refguide/data-grid-document-template'
objectredirect 'refguide/Sort+Bar' '/refguide/sort-bar'
objectredirect 'refguide/Columns+(document+template)' '/refguide/columns-document-template'
objectredirect 'refguide/Dynamic+Image+(document+template)' '/refguide/dynamic-image-document-template'
objectredirect 'refguide/dynamic-image-(document-template)' '/refguide/dynamic-image-document-template'
objectredirect 'refguide/Data+View+(document+template)' '/refguide/data-view-document-template'
objectredirect 'refguide/data-view-(document-template)' '/refguide/data-view-document-template'
objectredirect 'refguide/Document+Templates' '/refguide/document-templates'
objectredirect 'refguide/tab-page' '/refguide/tab-container'
objectredirect 'refguide/action-button' '/refguide/button-widgets'
objectredirect 'refguide/drop-down-button' '/refguide/button-widgets'
objectredirect 'refguide/image-property' '/refguide/image'
objectredirect 'refguide/grid-action-button' '/refguide/control-bar'
objectredirect 'refguide/remove-button' '/refguide/control-bar'
objectredirect 'refguide/select-button' '/refguide/control-bar'
objectredirect 'refguide/add-button' '/refguide/control-bar'
objectredirect 'refguide/deselect-all-button' '/refguide/control-bar'
objectredirect 'refguide/export-to-csv-button' '/refguide/control-bar'
objectredirect 'refguide/export-to-excel-button' '/refguide/control-bar'
objectredirect 'refguide/grid-new-button' '/refguide/control-bar'
objectredirect 'refguide/search-button' '/refguide/control-bar'
objectredirect 'refguide/select-all-button' '/refguide/control-bar'
objectredirect 'refguide/comparison-search-field' '/refguide/search-bar'
objectredirect 'refguide/drop-down-search-field' '/refguide/search-bar'
objectredirect 'refguide/range-search-field' '/refguide/search-bar'
objectredirect 'refguide/opening-pages' '/refguide/on-click-event'
objectredirect 'refguide/starting-microflows' '/refguide/on-click-event'
objectredirect 'refguide/app-settings-dialog' '/refguide/new-project'
objectredirect 'refguide/annotation-flow' '/refguide/annotation'
objectredirect 'refguide/close-form' '/refguide/close-page'
objectredirect 'refguide/columns-(document-template)' '/refguide/columns-document-template'
objectredirect 'refguide/consumed-odata-services' '/refguide/published-odata-services'
objectredirect 'refguide/data-grid-(document-template)' '/refguide/data-grid-document-template'
objectredirect 'refguide/module-role' '/refguide/module-security'
objectredirect 'refguide/page-template' '/refguide/page-templates'
objectredirect 'refguide/user-role' '/refguide/user-roles'
objectredirect 'refguide/link-button' '/refguide/button-widgets'
objectredirect 'refguide/sign-out-button' '/refguide/button-widgets'
#    /****************************************************
#     * From Desktop Modeler version 7 (permanent, mapped)
#     ****************************************************/
objectredirect 'refguide7/modeler' '/refguide7/desktop-modeler-overview'
objectredirect 'refguide7/Modeler' '/refguide7/desktop-modeler-overview'
objectredirect 'refguide7/desktop-webmodeler' '/refguide7/collaborative-development'
objectredirect 'web-modeler/general-sync-webmodeler-desktopmodeler-wm' '/refguide7/collaborative-development'
objectredirect 'howto/web-modeler/syncing-webmodeler-desktop' '/refguide7/collaborative-development'
objectredirect 'refguide7/sync-webmodeler-desktopmodeler' '/refguide7/collaborative-development'
objectredirect 'refguide7/download-from-team-server-dialog' '/refguide7/download-from-version-control-dialog'
objectredirect 'refguide7/open-project-dialog' '/refguide7/open-app-dialog'
objectredirect 'refguide7/upload-to-team-server-dialog' '/refguide7/upload-to-version-control-dialog'
objectredirect 'refguide7/microflow-expressions' '/refguide7/expressions'
objectredirect 'deployment/cloud-foundry/index' '/developerportal/deploy/cloud-foundry-deploy'
objectredirect 'howto7/solving-load-and-import-errors' '/howto7/monitoring-troubleshooting/solving-load-and-import-errors'
objectredirect 'refguide7/drop-down-widget' '/refguide7/drop_down'
objectredirect 'refguide7/horizontal-split-pane' '/refguide7/scroll-container'
objectredirect 'refguide7/vertical-split-pane' '/refguide7/scroll-container'
objectredirect 'refguide7/Select++Elements' '/refguide7/select--elements'
objectredirect 'refguide7/Developing+Hybrid+Mobile+Apps' '/refguide7/developing-hybrid-mobile-apps'
objectredirect 'howto7/deploying-a-mendix-app-to-cloud-foundry' '/developerportal/deploy/cloud-foundry-deploy'
objectredirect 'refguide7/Show+Page' '/refguide7/show-page'
objectredirect 'refguide7/Validation+Feedback' '/refguide7/validation-feedback'
objectredirect 'refguide7/Show+Message' '/refguide7/show-message'
objectredirect 'refguide7/Show+Home+Page' '/refguide7/show-home-page'
objectredirect 'refguide7/Download+File' '/refguide7/download-file'
objectredirect 'refguide7/Close+Form' '/refguide7/close-page'
objectredirect 'refguide7/Row+(document+template)' '/refguide7/row-document-template'
objectredirect 'refguide7/Table+(document+template' '/refguide7/table-document-template'
objectredirect 'refguide7/Cell+(document+template)' '/refguide7/cell-document-template'
objectredirect 'refguide7/Static+Image+(document+template)' '/refguide7/static-image-document-template'
objectredirect 'refguide7/Title+(document+template)' '/refguide7/title-document-template'
objectredirect 'refguide7/Static+label+(document+template)' '/refguide7/static-label-document-template'
objectredirect 'refguide7/Page+Break+(document+template)' '/refguide7/page-break-document-template'
objectredirect 'refguide7/Line+Break+(document+template)' '/refguide7/line-break-document-template'
objectredirect 'refguide7/Header+(document+template)' '/refguide7/header-document-template'
objectredirect 'refguide7/Footer+(document+template)' '/refguide7/footer-document-template'
objectredirect 'refguide7/Dynamic+label+(document+template)' '/refguide7/dynamic-label-document-template'
objectredirect 'refguide7/Template+Grid+(document+template)' '/refguide7/template-grid-document-template'
objectredirect 'refguide7/Data+Grid+(document+template)' '/refguide7/data-grid-document-template'
objectredirect 'refguide7/Sort+Bar' '/refguide7/sort-bar'
objectredirect 'refguide7/Columns+(document+template)' '/refguide7/columns-document-template'
objectredirect 'refguide7/Dynamic+Image+(document+template)' '/refguide7/dynamic-image-document-template'
objectredirect 'refguide7/Data+View+(document+template)' '/refguide7/data-view-document-template'
objectredirect 'refguide7/Document+Templates' '/refguide7/document-templates'
objectredirect 'refguide7/link-button' '/refguide7/action-button'
objectredirect 'refguide7/sign-out-button' '/refguide7/button-widgets'
#	/****************************************************
#     * From Desktop Modeler version 6 (permanent)
#     ****************************************************/
objectredirect 'refguide6/Reference+Guide+6' '/refguide6/'
objectredirect 'refguide6/Modeler' '/refguide6/modeler'
objectredirect 'refguide6/TreeNavigation' '/refguide6/'
objectredirect 'refguide6/Access+Rules' '/refguide6/access-rules'
objectredirect 'refguide6/Action+Button' '/refguide6/action-button'
objectredirect 'refguide6/Action+Call+Activities' '/refguide6/action-call-activities'
objectredirect 'refguide6/Actions' '/refguide6/actions'
objectredirect 'refguide6/Activities' '/refguide6/activities'
objectredirect 'refguide6/Add+button' '/refguide6/add-button'
objectredirect 'refguide6/Add+date+function+calls' '/refguide6/add-date-function-calls'
objectredirect 'refguide6/Administrator' '/refguide6/administrator'
objectredirect 'refguide6/Aggregate+List' '/refguide6/aggregate-list'
objectredirect 'refguide6/Annotation' '/refguide6/annotation'
objectredirect 'refguide6/Annotation+flow' '/refguide6/annotation-flow'
objectredirect 'refguide6/Annotations' '/refguide6/annotations'
objectredirect 'refguide6/Anonymous+Users' '/refguide6/anonymous-users'
objectredirect 'refguide6/App+Platform' '/refguide6/app-platform'
objectredirect 'refguide6/App+Settings+Dialog' '/refguide6/app-settings-dialog'
objectredirect 'refguide6/Arithmetic+expressions' '/refguide6/arithmetic-expressions'
objectredirect 'refguide6/Association+Source' '/refguide6/association-source'
objectredirect 'refguide6/Associations' '/refguide6/associations'
objectredirect 'refguide6/Attributes' '/refguide6/attributes'
objectredirect 'refguide6/Back+button' '/refguide6/back-button'
objectredirect 'refguide6/Basic+Reports' '/refguide6/basic-reports'
objectredirect 'refguide6/Between+date+function+calls' '/refguide6/between-date-function-calls'
objectredirect 'refguide6/Boolean+expressions' '/refguide6/boolean-expressions'
objectredirect 'refguide6/Branch+Line+Manager+Dialog' '/refguide6/branch-line-manager-dialog'
objectredirect 'refguide6/Break+Event' '/refguide6/break-event'
objectredirect 'refguide6/Button+Widgets' '/refguide6/button-widgets'
objectredirect 'refguide6/Call+Rest+Action' '/refguide6/call-rest-action'
objectredirect 'refguide6/Call+Web+Service' '/refguide6/call-web-service'
objectredirect 'refguide6/Call+Web+Service+Action' '/refguide6/call-web-service-action'
objectredirect 'refguide6/Cancel+button' '/refguide6/cancel-button'
objectredirect 'refguide6/Cast+Object' '/refguide6/cast-object'
objectredirect 'refguide6/Cell+Document+Template' '/refguide6/cell-document-template'
objectredirect 'refguide6/certificates' '/developerportal/deploy/certificates'
objectredirect 'refguide6/Change+List' '/refguide6/change-list'
objectredirect 'refguide6/Change+Object' '/refguide6/change-object'
objectredirect 'refguide6/Change+Variable' '/refguide6/change-variable'
objectredirect 'refguide6/Check+box' '/refguide6/check-box'
objectredirect 'refguide6/Client+Activities' '/refguide6/client-activities'
objectredirect 'refguide6/Close+Form' '/refguide6/close-form'
objectredirect 'refguide6/Close+page+button' '/refguide6/close-page-button'
objectredirect 'refguide6/Clustered+Mendix+Runtime' '/refguide6/clustered-mendix-runtime'
objectredirect 'refguide6/Clustered+Mendix+Business+Server' '/refguide6/clustered-mendix-runtime'
objectredirect 'refguide6/Columns' '/refguide6/columns'
objectredirect 'refguide6/Columns+Document+Template' '/refguide6/columns-document-template'
objectredirect 'refguide6/Commit+Dialog' '/refguide6/commit-dialog'
objectredirect 'refguide6/Commit+Object(s)' '/refguide6/committing-objects'
objectredirect 'refguide6/Committing+Objects' '/refguide6/committing-objects'
objectredirect 'refguide6/Common+Widget+Properties' '/refguide6/common-widget-properties'
objectredirect 'refguide6/Common+Widgets' '/refguide6/common-widgets'
objectredirect 'refguide6/Comparison+Search+Field' '/refguide6/comparison-search-field'
objectredirect 'refguide6/Conditions' '/refguide6/conditions'
objectredirect 'refguide6/Configuration' '/refguide6/configuration'
objectredirect 'refguide6/Configuring+Hybrid+Mobile+Apps+To+Run+Offline' '/refguide6/configuring-hybrid-mobile-apps-to-run-offline'
objectredirect 'refguide6/Constants' '/refguide6/constants'
objectredirect 'refguide6/Consumed+App+Services' '/refguide6/consumed-app-services'
objectredirect 'refguide6/Consumed+REST+Services' '/refguide6/consumed-rest-services'
objectredirect 'refguide6/Consumed+web+service' '/refguide6/consumed-web-service'
objectredirect 'refguide6/Consumed+Web+Services' '/refguide6/consumed-web-services'
objectredirect 'refguide6/Container' '/refguide6/container'
objectredirect 'refguide6/Container+Widgets' '/refguide6/container-widgets'
objectredirect 'refguide6/Context+Mechanism' '/refguide6/context-mechanism'
objectredirect 'refguide6/Continue+Event' '/refguide6/continue-event'
objectredirect 'refguide6/Control+Bar' '/refguide6/control-bar'
objectredirect 'refguide6/Create+Branch+Line+Dialog' '/refguide6/create-branch-line-dialog'
objectredirect 'refguide6/Create+Deployment+Package+Dialog' '/refguide6/create-deployment-package-dialog'
objectredirect 'refguide6/Create+List' '/refguide6/create-list'
objectredirect 'refguide6/Create+Object' '/refguide6/create-object'
objectredirect 'refguide6/Create+Variable' '/refguide6/create-variable'
objectredirect 'refguide6/Custom+Settings' '/refguide6/custom-settings'
objectredirect 'refguide6/Customizing+Hybrid+Mobile+Apps' '/refguide6/customizing-hybrid-mobile-apps'
objectredirect 'refguide6/Customizing+PhoneGap+Build+packages' '/refguide6/customizing-phonegap-build-packages'
objectredirect 'refguide6/Data+grid' '/refguide6/data-grid'
objectredirect 'refguide6/Data+Grid+Document+Template' '/refguide6/data-grid-document-template'
objectredirect 'refguide6/Data+Sets' '/refguide6/data-sets'
objectredirect 'refguide6/Data+Sources' '/refguide6/data-sources'
objectredirect 'refguide6/Data+Storage' '/refguide6/data-storage'
objectredirect 'refguide6/Data+Types' '/refguide6/data-types'
objectredirect 'refguide6/Data+view' '/refguide6/data-view'
objectredirect 'refguide6/Data+view+action+button' '/refguide6/data-view-action-button'
objectredirect 'refguide6/Data+view+cancel+button' '/refguide6/data-view-cancel-button'
objectredirect 'refguide6/Data+view+close+button' '/refguide6/data-view-close-button'
objectredirect 'refguide6/Data+view+control+bar' '/refguide6/data-view-control-bar'
objectredirect 'refguide6/Data+View+Document+Template' '/refguide6/data-view-document-template'
objectredirect 'refguide6/Data+view+save+button' '/refguide6/data-view-save-button'
objectredirect 'refguide6/Data+Widgets' '/refguide6/data-widgets'
objectredirect 'refguide6/Database+Source' '/refguide6/database-source'
objectredirect 'refguide6/Date+and+Time+Handling+in+3.0' '/refguide6/date-and-time-handling-in-3.0'
objectredirect 'refguide6/Date+creation' '/refguide6/date-creation'
objectredirect 'refguide6/Date+picker' '/refguide6/date-picker'
objectredirect 'refguide6/Date+Range+Field' '/refguide6/date-range-field'
objectredirect 'refguide6/Date+Range+Selector' '/refguide6/date-range-selector'
objectredirect 'refguide6/DateTime+handling+FAQ' '/refguide6/datetime-handling-faq'
objectredirect 'refguide6/DB2' '/refguide6/db2'
objectredirect 'refguide6/Delete+button' '/refguide6/delete-button'
objectredirect 'refguide6/Delete+Object(s)' '/refguide6/deleting-objects'
objectredirect 'refguide6/Deleting+Objects' '/refguide6/deleting-objects'
objectredirect 'refguide6/Demo+Users' '/refguide6/demo-users'
objectredirect 'refguide6/Deploy+To+The+Cloud+Dialog' '/refguide6/deploy-to-the-cloud-dialog'
objectredirect 'refguide6/Deselect+all+button' '/refguide6/deselect-all-button'
objectredirect 'refguide6/Desktop+profile' '/refguide6/desktop-profile'
objectredirect 'refguide6/Developing+Hybrid+Mobile+Apps' '/refguide6/developing-hybrid-mobile-apps'
objectredirect 'refguide6/Dialogs' '/refguide6/dialogs'
objectredirect 'refguide6/Document+Generation+Activities' '/refguide6/document-generation-activities'
objectredirect 'refguide6/Document+Template' '/refguide6/document-template'
objectredirect 'refguide6/Document+Templates' '/refguide6/document-templates'
objectredirect 'refguide6/Domain+Model' '/refguide6/domain-model'
objectredirect 'refguide6/Download+File' '/refguide6/download-file'
objectredirect 'refguide6/Download+From+Team+Server+Dialog' '/refguide6/download-from-team-server-dialog'
objectredirect 'refguide6/Drop+Down+Widget' '/refguide6/drop_down'
objectredirect 'refguide6/Drop+Down' '/refguide6/drop-down'
objectredirect 'refguide6/Drop+down+button' '/refguide6/drop-down-button'
objectredirect 'refguide6/Drop+Down+Search+Field' '/refguide6/drop-down-search-field'
objectredirect 'refguide6/Dynamic+Image+Document+Template' '/refguide6/dynamic-image-document-template'
objectredirect 'refguide6/Dynamic+Label+Document+Template' '/refguide6/dynamic-label-document-template'
objectredirect 'refguide6/Edit+button' '/refguide6/edit-button'
objectredirect 'refguide6/Edit+Cloud+Foundry+Settings+Dialog' '/refguide6/edit-cloud-foundry-settings-dialog'
objectredirect 'refguide6/End+Event' '/refguide6/end-event'
objectredirect 'refguide6/Entities' '/refguide6/entities'
objectredirect 'refguide6/Entity+Path+Source' '/refguide6/entity-path-source'
objectredirect 'refguide6/Enumeration+Values' '/refguide6/enumeration-values'
objectredirect 'refguide6/Enumerations' '/refguide6/enumerations'
objectredirect 'refguide6/Enumerations+in+microflow+expressions' '/refguide6/enumerations-in-microflow-expressions'
objectredirect 'refguide6/Error+Event' '/refguide6/error-event'
objectredirect 'refguide6/Event+Handlers' '/refguide6/event-handlers'
objectredirect 'refguide6/Exclusive+Split' '/refguide6/exclusive-split'
objectredirect 'refguide6/Export+Mapping+Action' '/refguide6/export-mapping-action'
objectredirect 'refguide6/Export+Mappings' '/refguide6/export-mappings'
objectredirect 'refguide6/Export+to+CSV+button' '/refguide6/export-to-csv-button'
objectredirect 'refguide6/Export+to+excel+button' '/refguide6/export-to-excel-button'
objectredirect 'refguide6/Export+XML' '/refguide6/export-xml'
objectredirect 'refguide6/File+manager' '/refguide6/file-manager'
objectredirect 'refguide6/File+Widgets' '/refguide6/file-widgets'
objectredirect 'refguide6/Footer+Document+Template' '/refguide6/footer-document-template'
objectredirect 'refguide6/Garbage+collection' '/refguide6/garbage-collection'
objectredirect 'refguide6/General' '/refguide6/general'
objectredirect 'refguide6/Generate+Document' '/refguide6/generate-document'
objectredirect 'refguide6/Getting+the+Mendix+Developer+App' '/refguide6/getting-the-mendix-developer-app'
objectredirect 'refguide6/Grid+action+button' '/refguide6/grid-action-button'
objectredirect 'refguide6/Grid+microflow+button' '/refguide6/grid-microflow-button'
objectredirect 'refguide6/Grid+New+Button' '/refguide6/grid-new-button'
objectredirect 'refguide6/Group+box' '/refguide6/group-box'
objectredirect 'refguide6/Section' '/refguide6/group-box'
objectredirect 'refguide6/Header' '/refguide6/header'
objectredirect 'refguide6/Header+Document+Template' '/refguide6/header-document-template'
objectredirect 'refguide6/History+Dialog' '/refguide6/history-dialog'
objectredirect 'refguide6/Horizontal+Split+Pane' '/refguide6/horizontal-split-pane'
objectredirect 'refguide6/If+expressions' '/refguide6/if-expressions'
objectredirect 'refguide6/Image' '/refguide6/image'
objectredirect 'refguide6/Image+uploader' '/refguide6/image-uploader'
objectredirect 'refguide6/Image+viewer' '/refguide6/image-viewer'
objectredirect 'refguide6/Images+refguide' '/refguide6/images'
objectredirect 'refguide6/Images' '/refguide6/images'
objectredirect 'refguide6/Image+Property' '/refguide6/image-property'
objectredirect 'refguide6/Import+Mapping+Action' '/refguide6/import-mapping-action'
objectredirect 'refguide6/Import+Mappings' '/refguide6/import-mappings'
objectredirect 'refguide6/Import+XML' '/refguide6/import-xml'
objectredirect 'refguide6/Inheritance+Split' '/refguide6/inheritance-split'
objectredirect 'refguide6/Indexes' '/refguide6/indexes'
objectredirect 'refguide6/Input+reference+set+selector' '/refguide6/input-reference-set-selector'
objectredirect 'refguide6/Input+Widgets' '/refguide6/input-widgets'
objectredirect 'refguide6/Integration' '/refguide6/integration'
objectredirect 'refguide6/Integration+Activities' '/refguide6/integration-activities'
objectredirect 'refguide6/ISession+API+Usage' '/refguide6/isession-api-usage'
objectredirect 'refguide6/Java+Action+Call' '/refguide6/java-action-call'
objectredirect 'refguide6/Java+Actions' '/refguide6/java-actions'
objectredirect 'refguide6/Java+Memory+Usage+With+Mendix' '/refguide6/java-memory-usage-with-mendix'
objectredirect 'refguide6/Java+Programming' '/refguide6/java-programming'
objectredirect 'refguide6/JSON+Structures' '/refguide6/json-structures'
objectredirect 'refguide6/Keep+alive+mechanism+for+Persistent+Sessions' '/refguide6/keep-alive-mechanism-for-persistent-sessions'
objectredirect 'refguide6/Label' '/refguide6/label'
objectredirect 'refguide6/Layout' '/refguide6/layout'
objectredirect 'refguide6/Layouts' '/refguide6/layout'
objectredirect 'refguide6/Layout+grid' '/refguide6/layout-grid'
objectredirect 'refguide6/Layout+Widgets' '/refguide6/layout-widgets'
objectredirect 'refguide6/Line+Break+Document+Template' '/refguide6/line-break-document-template'
objectredirect 'refguide6/Link+button' '/refguide6/link-button'
objectredirect 'refguide6/List+Activities' '/refguide6/list-activities'
objectredirect 'refguide6/List+Operation' '/refguide6/list-operation'
objectredirect 'refguide6/List+view' '/refguide6/list-view'
objectredirect 'refguide6/Listen+To+Grid+Source' '/refguide6/listen-to-grid-source'
objectredirect 'refguide6/Log+Message' '/refguide6/log-message'
objectredirect 'refguide6/Logging' '/refguide6/logging'
objectredirect 'refguide6/Logging+Activities' '/refguide6/logging-activities'
objectredirect 'refguide6/Loop' '/refguide6/loop'
objectredirect 'refguide6/Managing+App+Signing+Keys' '/refguide6/managing-app-signing-keys'
objectredirect 'refguide6/Map+Automatically' '/refguide6/map-automatically'
objectredirect 'refguide6/Mapping+Documents' '/refguide6/mapping-documents'
objectredirect 'refguide6/Mathematical+function+calls' '/refguide6/mathematical-function-calls'
objectredirect 'refguide6/Menu' '/refguide6/menu'
objectredirect 'refguide6/Menu+Bar' '/refguide6/menu-bar'
objectredirect 'refguide6/Menu+Item' '/refguide6/menu-item'
objectredirect 'refguide6/Menu+Widgets' '/refguide6/menu-widgets'
objectredirect 'refguide6/Merge' '/refguide6/merge'
objectredirect 'refguide6/Merge+Dialog' '/refguide6/merge-dialog'
objectredirect 'refguide6/Microflow' '/refguide6/microflow'
objectredirect 'refguide6/Microflow+Activities' '/refguide6/microflow-activities'
objectredirect 'refguide6/Microflow+Call' '/refguide6/microflow-call'
objectredirect 'refguide6/Microflow+Element+Common+Properties' '/refguide6/microflow-element-common-properties'
objectredirect 'refguide6/Microflow+Expressions' '/refguide6/microflow-expressions'
objectredirect 'refguide6/Microflow+Source' '/refguide6/microflow-source'
objectredirect 'refguide6/Microflows' '/refguide6/microflows'
objectredirect 'refguide6/Mobile' '/refguide6/mobile'
objectredirect 'refguide6/Modeler' '/refguide6/modeler'
objectredirect 'refguide6/Module+Role' '/refguide6/module-role'
objectredirect 'refguide6/Module+Security' '/refguide6/module-security'
objectredirect 'refguide6/Module+Status' '/refguide6/module-status'
objectredirect 'refguide6/Modules' '/refguide6/modules'
objectredirect 'refguide6/Monitoring+-+Mendix+Runtime' '/refguide6/monitoring-mendix-runtime'
objectredirect 'refguide6/Monitoring+-+Mendix+Business+Server' '/refguide6/monitoring-mendix-runtime'
objectredirect 'refguide6/Monitoring+-+What+to+monitor' '/refguide6/monitoring-what-to-monitor'
objectredirect 'refguide6/Moving+from+5+to+6' '/refguide6/moving-from-5-to-6'
objectredirect 'refguide6/MySQL' '/refguide6/mysql'
objectredirect 'refguide6/Navigation' '/refguide6/navigation'
objectredirect 'refguide6/Navigation+list' '/refguide6/navigation-list'
objectredirect 'refguide6/Navigation+Tree' '/refguide6/navigation-tree'
objectredirect 'refguide6/New+button' '/refguide6/new-button'
objectredirect 'refguide6/NULL+Ordering+Behavior' '/refguide6/null-ordering-behavior'
objectredirect 'refguide6/Numeric+formatting' '/refguide6/numeric-formatting'
objectredirect 'refguide6/Object+Activities' '/refguide6/object-activities'
objectredirect 'refguide6/OData+Query+Options' '/refguide6/odata-query-options'
objectredirect 'refguide6/OData+Representation' '/refguide6/odata-representation'
objectredirect 'refguide6/Offline' '/refguide6/offline'
objectredirect 'refguide6/Offline+device+profile' '/refguide6/offline-device-profile'
objectredirect 'refguide6/On+Click+Event' '/refguide6/on-click-event'
objectredirect 'refguide6/Open+Project+Dialog' '/refguide6/open-project-dialog'
objectredirect 'refguide6/Opening+Pages' '/refguide6/opening-pages'
objectredirect 'refguide6/Operations' '/refguide6/operations'
objectredirect 'refguide6/OQL' '/refguide6/oql'
objectredirect 'refguide6/OQL+Aggregation' '/refguide6/oql-aggregation'
objectredirect 'refguide6/OQL+Case+Expression' '/refguide6/oql-case-expression'
objectredirect 'refguide6/OQL+CAST' '/refguide6/oql-cast'
objectredirect 'refguide6/OQL+COALESCE' '/refguide6/oql-coalesce'
objectredirect 'refguide6/OQL+DATEDIFF' '/refguide6/oql-datediff'
objectredirect 'refguide6/OQL+DATEPART' '/refguide6/oql-datepart'
objectredirect 'refguide6/OQL+Expressions' '/refguide6/oql-expressions'
objectredirect 'refguide6/OQL+From+Clause' '/refguide6/oql-from-clause'
objectredirect 'refguide6/OQL+FULL+OUTER+JOIN' '/refguide6/oql-full-outer-join'
objectredirect 'refguide6/OQL+Functions' '/refguide6/oql-functions'
objectredirect 'refguide6/OQL+Group+by+Clause' '/refguide6/oql-group-by-clause'
objectredirect 'refguide6/OQL+INNER+JOIN' '/refguide6/oql-inner-join'
objectredirect 'refguide6/OQL+LEFT+OUTER+JOIN' '/refguide6/oql-left-outer-join'
objectredirect 'refguide6/OQL+LENGTH' '/refguide6/oql-length'
objectredirect 'refguide6/OQL+Limit+Clause' '/refguide6/oql-limit-clause'
objectredirect 'refguide6/OQL+Operators' '/refguide6/oql-operators'
objectredirect 'refguide6/OQL+Order+by+Clause' '/refguide6/oql-order-by-clause'
objectredirect 'refguide6/OQL+Parameters' '/refguide6/oql-parameters'
objectredirect 'refguide6/OQL+RANGEBEGIN' '/refguide6/oql-rangebegin'
objectredirect 'refguide6/OQL+RANGEEND' '/refguide6/oql-rangeend'
objectredirect 'refguide6/OQL+RIGHT+OUTER+JOIN' '/refguide6/oql-right-outer-join'
objectredirect 'refguide6/OQL+ROUND' '/refguide6/oql-round'
objectredirect 'refguide6/OQL+Select+Clause' '/refguide6/oql-select-clause'
objectredirect 'refguide6/OQL+Where+Clause' '/refguide6/oql-where-clause'
objectredirect 'refguide6/Oracle' '/refguide6/oracle'
objectredirect 'refguide6/Packaging+Hybrid+Mobile+Apps' '/refguide6/packaging-hybrid-mobile-apps'
objectredirect 'refguide6/Page' '/refguide6/page'
objectredirect 'refguide6/Page+Break+Document+Template' '/refguide6/page-break-document-template'
objectredirect 'refguide6/Page+Concepts' '/refguide6/page-concepts'
objectredirect 'refguide6/Page+Templates' '/refguide6/page-templates'
objectredirect 'refguide6/Page+title' '/refguide6/page-title'
objectredirect 'refguide6/Pages' '/refguide6/pages'
objectredirect 'refguide6/Parameter' '/refguide6/parameter'
objectredirect 'refguide6/Parse+and+format+date+function+calls' '/refguide6/parse-and-format-date-function-calls'
objectredirect 'refguide6/Parse+and+format+decimal+function+calls' '/refguide6/parse-and-format-decimal-function-calls'
objectredirect 'refguide6/Parse+and+format+float+function+calls' '/refguide6/parse-and-format-float-function-calls'
objectredirect 'refguide6/Parse+integer' '/refguide6/parse-integer'
objectredirect 'refguide6/Password+Policy' '/refguide6/password-policy'
objectredirect 'refguide6/Persistability' '/refguide6/persistability'
objectredirect 'refguide6/Phone+profile' '/refguide6/phone-profile'
objectredirect 'refguide6/Placeholder' '/refguide6/placeholder'
objectredirect 'refguide6/Preferences+Dialog' '/refguide6/preferences-dialog'
objectredirect 'refguide6/Proactive+Maintenance' '/refguide6/proactive-maintenance'
objectredirect 'refguide6/Project' '/refguide6/project'
objectredirect 'refguide6/Project+Security' '/refguide6/project-security'
objectredirect 'refguide6/Project+Settings' '/refguide6/project-settings'
objectredirect 'refguide6/Publish+Packages+To+Mobile+Stores' '/refguide6/publish-packages-to-mobile-stores'
objectredirect 'refguide6/Published+App+Service' '/refguide6/published-app-service'
objectredirect 'refguide6/Published+App+Services' '/refguide6/published-app-services'
objectredirect 'refguide6/Published+OData+resource' '/refguide6/published-odata-resource'
objectredirect 'refguide6/Published+OData+Services' '/refguide6/published-odata-services'
objectredirect 'refguide6/Published+web+service' '/refguide6/published-web-service'
objectredirect 'refguide6/Published+Web+Services' '/refguide6/published-web-services'
objectredirect 'refguide6/Radio+buttons' '/refguide6/radio-buttons'
objectredirect 'refguide6/Range+Search+Field' '/refguide6/range-search-field'
objectredirect 'refguide6/Reference+selector' '/refguide6/reference-selector'
objectredirect 'refguide6/Reference+set+selector' '/refguide6/reference-set-selector'
objectredirect 'refguide6/Regular+Expressions' '/refguide6/regular-expressions'
objectredirect 'refguide6/Relational+expressions' '/refguide6/relational-expressions'
objectredirect 'refguide6/Remove+button' '/refguide6/remove-button'
objectredirect 'refguide6/Removed+APIs' '/refguide6/removed-apis'
objectredirect 'refguide6/Report+Button' '/refguide6/report-button'
objectredirect 'refguide6/Report+Chart' '/refguide6/report-chart'
objectredirect 'refguide6/Report+Date+Parameter' '/refguide6/report-date-parameter'
objectredirect 'refguide6/Report+Grid' '/refguide6/report-grid'
objectredirect 'refguide6/Report+Pane' '/refguide6/report-pane'
objectredirect 'refguide6/Report+Parameter' '/refguide6/report-parameter'
objectredirect 'refguide6/Report+Widgets' '/refguide6/report-widgets'
objectredirect 'refguide6/Reporting' '/refguide6/report-widgets'
objectredirect 'refguide6/Retrieve' '/refguide6/retrieve'
objectredirect 'refguide6/Review+log+files+-+MS+IIS+Server' '/refguide6/review-log-files-ms-iis-server'
objectredirect 'refguide6/Review+log+files+-+MS+SQL+Server' '/refguide6/review-log-files-ms-sql-server'
objectredirect 'refguide6/Rollback+Object' '/refguide6/rollback-object'
objectredirect 'refguide6/Row+Document+Template' '/refguide6/row-document-template'
objectredirect 'refguide6/Rules' '/refguide6/rules'
objectredirect 'refguide6/Runtime' '/refguide6/runtime'
objectredirect 'refguide6/Save+button' '/refguide6/save-button'
objectredirect 'refguide6/Scheduled+Events' '/refguide6/scheduled-events'
objectredirect 'refguide6/Scroll+Container' '/refguide6/scroll-container'
objectredirect 'refguide6/Scroll+Container+Region' '/refguide6/scroll-container-region'
objectredirect 'refguide6/Search+Bar' '/refguide6/search-bar'
objectredirect 'refguide6/Search+button' '/refguide6/search-button'
objectredirect 'refguide6/Security' '/refguide6/security'
objectredirect 'refguide6/Select++Elements' '/refguide6/select--elements'
objectredirect 'refguide6/Select+all+button' '/refguide6/select-all-button'
objectredirect 'refguide6/Select+app+service' '/refguide6/select-app-service'
objectredirect 'refguide6/Select+button' '/refguide6/select-button'
objectredirect 'refguide6/Sequence+Flow' '/refguide6/sequence-flow'
objectredirect 'refguide6/Settings' '/refguide6/settings'
objectredirect 'refguide6/Show+Home+Page' '/refguide6/show-home-page'
objectredirect 'refguide6/Show+Message' '/refguide6/show-message'
objectredirect 'refguide6/Show+Page' '/refguide6/show-page'
objectredirect 'refguide6/Sidebar+toggle+button' '/refguide6/sidebar-toggle-button'
objectredirect 'refguide6/Sign+In+Dialog' '/refguide6/sign-in-dialog'
objectredirect 'refguide6/Sign+out+button' '/refguide6/sign-out-button'
objectredirect 'refguide6/Simple+Menu+Bar' '/refguide6/simple-menu-bar'
objectredirect 'refguide6/Snippet' '/refguide6/snippet'
objectredirect 'refguide6/Snippet+Call' '/refguide6/snippet-call'
objectredirect 'refguide6/Sort+Bar' '/refguide6/sort-bar'
objectredirect 'refguide6/Special+checks' '/refguide6/special-checks'
objectredirect 'refguide6/Start+Event' '/refguide6/start-event'
objectredirect 'refguide6/Starting+Microflows' '/refguide6/starting-microflows'
objectredirect 'refguide6/Static+Image+Document+Template' '/refguide6/static-image-document-template'
objectredirect 'refguide6/Static+Label+Document+Template' '/refguide6/static-label-document-template'
objectredirect 'refguide6/String+function+calls' '/refguide6/string-function-calls'
objectredirect 'refguide6/Style' '/refguide6/style'
objectredirect 'refguide6/Sync+button' '/refguide6/sync-button'
objectredirect 'refguide6/System+Requirements' '/refguide6/system-requirements'
objectredirect 'refguide6/System+Texts' '/refguide6/system-texts'
objectredirect 'refguide6/Tab+container' '/refguide6/tab-container'
objectredirect 'refguide6/Tab+page' '/refguide6/tab-page'
objectredirect 'refguide6/Table' '/refguide6/table'
objectredirect 'refguide6/Table+cell' '/refguide6/table-cell'
objectredirect 'refguide6/Table+Document+Template' '/refguide6/table-document-template'
objectredirect 'refguide6/Table+row' '/refguide6/table-row'
objectredirect 'refguide6/Tablet+profile' '/refguide6/tablet-profile'
objectredirect 'refguide6/Team+Server' '/refguide6/team-server'
objectredirect 'refguide6/Team+Server+FAQ' '/refguide6/team-server-faq'
objectredirect 'refguide6/Template+grid' '/refguide6/template-grid'
objectredirect 'refguide6/Template+Grid+Document+Template' '/refguide6/template-grid-document-template'
objectredirect 'refguide6/Text' '/refguide6/text'
objectredirect 'refguide6/Text+area' '/refguide6/text-area'
objectredirect 'refguide6/Text+box' '/refguide6/text-box'
objectredirect 'refguide6/Third+Party+Licenses' '/refguide6/third-party-licenses'
objectredirect 'refguide6/Title+Document+Template' '/refguide6/title-document-template'
objectredirect 'refguide6/To+float' '/refguide6/to-float'
objectredirect 'refguide6/To+string' '/refguide6/to-string'
objectredirect 'refguide6/Transient+Objects+Garbage+Collecting' '/refguide6/transient-objects-garbage-collecting'
objectredirect 'refguide6/Translatable+Texts' '/refguide6/translatable-texts'
objectredirect 'refguide6/Trim+to+date' '/refguide6/trim-to-date'
objectredirect 'refguide6/Troubleshooting' '/refguide6/troubleshooting'
objectredirect 'refguide6/Unary+expressions' '/refguide6/unary-expressions'
objectredirect 'refguide6/Upload+To+Team+Server+Dialog' '/refguide6/upload-to-team-server-dialog'
objectredirect 'refguide6/User+Roles' '/refguide6/user-roles'
objectredirect 'refguide6/User+Role' '/refguide6/user-roles'
objectredirect 'refguide6/Using+a+proxy+to+call+a+webservice' '/refguide6/using-a-proxy-to-call-a-webservice'
objectredirect 'refguide6/Using+Eclipse' '/refguide6/using-eclipse'
objectredirect 'refguide6/Validation+Feedback' '/refguide6/validation-feedback'
objectredirect 'refguide6/Validation+Rules' '/refguide6/validation-rules'
objectredirect 'refguide6/Variable+Activities' '/refguide6/variable-activities'
objectredirect 'refguide6/Version+Control' '/refguide6/version-control'
objectredirect 'refguide6/Version+Control+Concepts' '/refguide6/version-control-concepts'
objectredirect 'refguide6/Version+Control+Scenarios' '/refguide6/version-control-scenarios'
objectredirect 'refguide6/version-downgrade-prevention' '/developerportal/deploy/version-downgrade-prevention'
objectredirect 'refguide6/Vertical+Split+Pane' '/refguide6/vertical-split-pane'
objectredirect 'refguide6/XML+Inheritance+and+Choice' '/refguide6/xml-inheritance-and-choice'
objectredirect 'refguide6/XML+Reference+Guide' '/refguide6/xml-reference-guide'
objectredirect 'refguide6/XML+Schema+Support' '/refguide6/xml-schema-support'
objectredirect 'refguide6/XML+Schemas' '/refguide6/xml-schemas'
objectredirect 'refguide6/XPath' '/refguide6/xpath'
objectredirect 'refguide6/XPath+avg' '/refguide6/xpath-avg'
objectredirect 'refguide6/XPath+Constraint+Functions' '/refguide6/xpath-constraint-functions'
objectredirect 'refguide6/XPath+Constraints' '/refguide6/xpath-constraints'
objectredirect 'refguide6/XPath+contains' '/refguide6/xpath-contains'
objectredirect 'refguide6/XPath+count' '/refguide6/xpath-count'
objectredirect 'refguide6/XPath+day+from+dateTime' '/refguide6/xpath-day-from-datetime'
objectredirect 'refguide6/XPath+day+of+year+from+dateTime' '/refguide6/xpath-day-of-year-from-datetime'
objectredirect 'refguide6/XPath+ends+with' '/refguide6/xpath-ends-with'
objectredirect 'refguide6/XPath+Expressions' '/refguide6/xpath-expressions'
objectredirect 'refguide6/XPath+false' '/refguide6/xpath-false'
objectredirect 'refguide6/XPath+hours+from+dateTime' '/refguide6/xpath-hours-from-datetime'
objectredirect 'refguide6/XPath+id' '/refguide6/xpath-id'
objectredirect 'refguide6/XPath+Keywords+and+System+Variables' '/refguide6/xpath-keywords-and-system-variables'
objectredirect 'refguide6/XPath+length' '/refguide6/xpath-length'
objectredirect 'refguide6/XPath+max' '/refguide6/xpath-max'
objectredirect 'refguide6/XPath+min' '/refguide6/xpath-min'
objectredirect 'refguide6/XPath+minutes+from+dateTime' '/refguide6/xpath-minutes-from-datetime'
objectredirect 'refguide6/XPath+month+from+dateTime' '/refguide6/xpath-month-from-datetime'
objectredirect 'refguide6/XPath+not' '/refguide6/xpath-not'
objectredirect 'refguide6/XPath+Operators' '/refguide6/xpath-operators'
objectredirect 'refguide6/XPath+quarter+from+dateTime' '/refguide6/xpath-quarter-from-datetime'
objectredirect 'refguide6/XPath+Query+Functions' '/refguide6/xpath-query-functions'
objectredirect 'refguide6/XPath+seconds+from+dateTime' '/refguide6/xpath-seconds-from-datetime'
objectredirect 'refguide6/XPath+Source' '/refguide6/xpath-source'
objectredirect 'refguide6/XPath+starts+with' '/refguide6/xpath-starts-with'
objectredirect 'refguide6/XPath+string+length' '/refguide6/xpath-string-length'
objectredirect 'refguide6/XPath+sum' '/refguide6/xpath-sum'
objectredirect 'refguide6/XPath+Tokens' '/refguide6/xpath-tokens'
objectredirect 'refguide6/XPath+true' '/refguide6/xpath-true'
objectredirect 'refguide6/XPath+week+from+dateTime' '/refguide6/xpath-week-from-datetime'
objectredirect 'refguide6/XPath+weekday+from+dateTime' '/refguide6/xpath-weekday-from-datetime'
objectredirect 'refguide6/XPath+year+from+dateTime' '/refguide6/xpath-year-from-datetime'
objectredirect 'howto6/Solving+Load+and+Import+Errors' '/howto6/solving-load-and-import-errors'
#	/****************************************************
#     * From Studio (potentially temporary until the support of old bundles stops, mapped)
#     ****************************************************/
objectredirect 'refguide/web-modeler/domain-models-association-properties-wm' '/studio/domain-models-association-properties'
objectredirect 'refguide/web-modeler' '/studio/'
objectredirect 'refguide/web-modeler/microflows-wm' '/studio/microflows'
objectredirect 'refguide/web-modeler/microflows-expressions-wm' '/studio/microflows-expressions'
objectredirect 'refguide/web-modeler/app-settings-wm' '/studio/settings-widget-overview'
objectredirect 'studio/general-collaborative-development' '/studio/collaborative-development'
#	/****************************************************
#     * From Developer Portal (permanent, mapped) 
#     ****************************************************/
objectredirect 'developerportal/settings/technical-contact' '/developerportal/company-app-roles/technical-contact'
objectredirect 'developerportal/general/technical-contact' '/developerportal/company-app-roles/technical-contact'
objectredirect 'deployment/mendixcloud/certificates' '/developerportal/deploy/certificates'
objectredirect 'refguide/certificates' '/developerportal/deploy/certificates'
objectredirect 'mendixcloud/monitoring-application-health' '/developerportal/operate/monitoring-application-health'
objectredirect 'developerportal/howto/deploying-to-the-cloud' '/developerportal/deploy/mendix-cloud-deploy'
objectredirect 'deployment/on-premises/deploy-mendix-on-microsoft-windows' '/developerportal/deploy/deploy-mendix-on-microsoft-windows'
objectredirect 'deployment/on-premises' '/developerportal/deploy/on-premises-design'
objectredirect 'developerportal/community-tools/the-mendix-job-board' '/developerportal/community-tools/mendix-job-board'
objectredirect 'refguide/publish-packages-to-mobile-stores' '/howto/mobile/publishing-a-mendix-hybrid-mobile-app-in-mobile-app-stores'
objectredirect 'refguide/team-server' '/developerportal/develop/team-server'
#	/****************************************************
#     * From Data Hub (permanent, mapped) 
#     ****************************************************/
objectredirect 'data-hub/data-hub-catalog/use-data-catalog' '/data-hub/share-data/index'
objectredirect 'datahub/general/share-data/index' '/data-hub/share-data/index'
objectredirect 'data-hub/data-catalog/index' '/data-hub/index'
#	/****************************************************
#     * From Strategic Partners Guide (permanent, mapped)
#     ****************************************************/
objectredirect 'howto/sap/use-sap-odata-model-creator' '/partners/sap/use-sap-odata-model-creator'
objectredirect 'refguide/siemens/mindsphere-module-details' '/partners/siemens/mindsphere-module-details'
#	/****************************************************
#     * From the App Store (permanent, mapped)
#     ****************************************************/
objectredirect 'community/app-store/use-app-store-content-in-the-modeler' '/appstore/general/app-store-content'
objectredirect 'developerportal/app-store/use-app-store-content-in-the-modeler' '/appstore/general/app-store-content'
objectredirect 'howto50/Contributing+to+a+GitHub+repository' '/howto/collaboration-requirements-management/contribute-to-a-github-repository'
objectredirect 'howto/collaboration-project-management/contribute-to-a-github-repository' '/howto/collaboration-requirements-management/contribute-to-a-github-repository'
objectredirect 'howto/ux/create-a-custom-theme-with-the-mendix-ui-framework' '/howto/front-end/atlas-ui'
objectredirect 'howto/front-end/create-a-custom-theme-with-the-mendix-ui-framework' '/howto/front-end/atlas-ui'
objectredirect 'releasenotes/desktop-modeler/index' '/releasenotes/studio-pro/'
objectredirect 'releasenotes/desktop-modeler/8.0' '/releasenotes/studio-pro/8.0'
objectredirect 'releasenotes/desktop-modeler/7.23' '/releasenotes/studio-pro/7.23'
objectredirect 'releasenotes/desktop-modeler/7.22' '/releasenotes/studio-pro/7.22'
objectredirect 'releasenotes/desktop-modeler/7.21' '/releasenotes/studio-pro/7.21'
objectredirect 'releasenotes/desktop-modeler/7.20' '/releasenotes/studio-pro/7.20'
objectredirect 'releasenotes/desktop-modeler/7.19' '/releasenotes/studio-pro/7.19'
objectredirect 'releasenotes/desktop-modeler/7.18' '/releasenotes/studio-pro/7.18'
objectredirect 'releasenotes/desktop-modeler/7.17' '/releasenotes/studio-pro/7.17'
objectredirect 'releasenotes/desktop-modeler/7.16' '/releasenotes/studio-pro/7.16'
objectredirect 'releasenotes/desktop-modeler/7.15' '/releasenotes/studio-pro/7.15'
objectredirect 'releasenotes/desktop-modeler/7.14' '/releasenotes/studio-pro/7.14'
objectredirect 'releasenotes/desktop-modeler/7.13' '/releasenotes/studio-pro/7.13'
objectredirect 'releasenotes/desktop-modeler/7.12' '/releasenotes/studio-pro/7.12'
objectredirect 'releasenotes/desktop-modeler/7.11' '/releasenotes/studio-pro/7.11'
objectredirect 'releasenotes/desktop-modeler/7.10' '/releasenotes/studio-pro/7.10'
objectredirect 'releasenotes/desktop-modeler/7.9' '/releasenotes/studio-pro/7.9'
objectredirect 'releasenotes/desktop-modeler/7.8' '/releasenotes/studio-pro/7.8'
objectredirect 'releasenotes/desktop-modeler/7.7' '/releasenotes/studio-pro/7.7'
objectredirect 'releasenotes/desktop-modeler/7.6' '/releasenotes/studio-pro/7.6'
objectredirect 'releasenotes/desktop-modeler/7.5' '/releasenotes/studio-pro/7.5'
objectredirect 'releasenotes/desktop-modeler/7.4' '/releasenotes/studio-pro/7.4'
objectredirect 'releasenotes/desktop-modeler/7.3' '/releasenotes/studio-pro/7.3'
objectredirect 'releasenotes/desktop-modeler/7.2' '/releasenotes/studio-pro/7.2'
objectredirect 'releasenotes/desktop-modeler/7.1' '/releasenotes/studio-pro/7.1'
objectredirect 'releasenotes/desktop-modeler/7.0' '/releasenotes/studio-pro/7.0'
objectredirect 'releasenotes/desktop-modeler/6.10' '/releasenotes/studio-pro/6.10'
objectredirect 'releasenotes/desktop-modeler/6.9' '/releasenotes/studio-pro/6.9'
objectredirect 'releasenotes/desktop-modeler/6.8' '/releasenotes/studio-pro/6.8'
objectredirect 'releasenotes/desktop-modeler/6.7' '/releasenotes/studio-pro/6.7'
objectredirect 'releasenotes/desktop-modeler/6.6' '/releasenotes/studio-pro/6.6'
objectredirect 'releasenotes/desktop-modeler/6.5' '/releasenotes/studio-pro/6.5'
objectredirect 'releasenotes/desktop-modeler/6.4' '/releasenotes/studio-pro/6.4'
objectredirect 'releasenotes/desktop-modeler/6.3' '/releasenotes/studio-pro/6.3'
objectredirect 'releasenotes/desktop-modeler/6.2' '/releasenotes/studio-pro/6.2'
objectredirect 'releasenotes/desktop-modeler/6.1' '/releasenotes/studio-pro/6.1'
objectredirect 'releasenotes/desktop-modeler/6.0' '/releasenotes/studio-pro/6.0'
#	/****************************************************
#     * From the Support Portal (permanent, mapped) 
#     ****************************************************/
objectredirect 'community/app-store-content-support' '/appstore/general/app-store-content-support'
objectredirect 'mendixcloud/custom-domains' '/developerportal/deploy/custom-domains'
objectredirect 'developerportal/howto/how-to-link-app-to-node' '/developerportal/deploy/licensing-apps'
objectredirect 'developerportal/howto/how-to-link-a-different-app-to-a-node' '/developerportal/deploy/licensing-apps'
objectredirect 'developerportal/support/new-app-request-template' '/developerportal/support/new-app-node-request-template'
objectredirect 'developerportal/support/export-a-project-package' '/refguide/export-project-package-dialog'
objectredirect 'developerportal/support/change-affected-apps' '/developerportal/support/prepare-your-project'
#	/****************************************************
#     * From Model SDK API (permanent, mapped)
#     ****************************************************/	
objectredirect 'refguide7/cell-(document-template)' '/refguide/cell-document-template'
objectredirect 'refguide7/close-form' '/refguide/close-page'
objectredirect 'refguide7/columns-(document-template)' '/refguide/columns-document-template'
objectredirect 'refguide7/consumed-odata-services' '/refguide/published-odata-services'
objectredirect 'refguide7/data-grid-(document-template)' '/refguide/data-grid-document-template'
objectredirect 'refguide7/data-view-(document-template)' '/refguide/data-view-document-template'
objectredirect 'refguide7/dynamic-image-(document-template)' '/refguide/dynamic-image-document-template'
objectredirect 'refguide7/dynamic-label-(document-template)' '/refguide/dynamic-label-document-template'
objectredirect 'refguide7/footer-(document-template)' '/refguide/footer-document-template'
objectredirect 'refguide7/header-(document-template)' '/refguide/header-document-template'
objectredirect 'refguide7/line-break-(document-template)' '/refguide/line-break-document-template'
objectredirect 'refguide7/page-break-(document-template)' '/refguide/page-break-document-template'
objectredirect 'refguide7/page-template' '/refguide/page-templates'
objectredirect 'refguide7/row-(document-template)' '/refguide/row-document-template'
objectredirect 'refguide7/static-image-(document-template)' '/refguide/static-image-document-template'
objectredirect 'refguide7/static-label-(document-template)' '/refguide/static-label-document-template'
objectredirect 'refguide7/table-(document-template)' '/refguide/table-document-template'
objectredirect 'refguide7/template-grid-(document-template)' '/refguide/template-grid-document-template'
objectredirect 'refguide7/title-(document-template)' '/refguide/title-document-template'


# Need to check these redirects - how do we implement them?
#	{
#	  from: "~*\\\/aqm\\\/",
#	  to: "/addons/aqm-addon/index",
#	  exact: true
#    },
#	{
#	  from: "~*\\\/apm\\\/",
#	  to: "/addons/apd-addon/index",
#	  exact: true
#    },
#	{
#	  from: "~*\\\/ats\\\/",
#	  to: "/addons/ats-addon/index",
#	  exact: true
#    },
#    {
#      from: "~\/refguide6\/Drop-down",
#      to: "/refguide6/drop_down",
#      "exact": true
#    },
#
# This one has a space in it
#
# objectredirect 'refguide6/Drop+Down Widget' '/refguide6/drop_down'
#

exit 0

# convert from redirects.js using this regular expression
# ^\s+\{\n\s+from: "/(.+)",\n\s+to: "(.+)"\n\s+\},
# and replace with
# objectredirect '$1' '$2'\n
#
# Then change the comments
# ^(\s+\/\*)
# #$1
# and
# ^(\s+\*)
# #$1
#
# Remove multiple spaces and newlines (\n\s*\n -> \n)
#
# Use howto and refguide instead of howto8 and refguide8
#
# file names with trailing slashes need to be redirected from index! (e.g. 'howto/tutorials/' needs to be 'howto/tutorials/index')
#
# check for commands still outstanding ({) and commands containing \