#!/usr/bin/env python3
"""
sync-html-timestamps.py
Updates HTML file timestamps to match git modification dates of source markdown files
and static files. This allows AWS S3 sync to use timestamps to determine which files
need updating.

WHAT THIS SCRIPT HANDLES:
- HTML pages generated from markdown files (based on url: field in front matter)
- Alias pages (based on aliases: field in front matter) - full HTML copies at old URLs
- Static files (images, attachments, fonts, etc.) copied from /static to /public

LIMITATIONS - The following Hugo-generated files are NOT handled by this script:
- sitemap.xml - Generated by Hugo at build time
- robots.txt - Generated by Hugo (enableRobotsTXT = true)
- rss.xml - Generated RSS feed
- 404.html - Special error page
- index.html (root homepage) - May not have explicit url: field
- CSS/JS bundles - Hugo-processed assets from themes and node_modules
- search.html and other Hugo special pages

These files will always have the build timestamp and will be synced on every deployment.
This is acceptable because:
1. They change infrequently
2. They are small files that upload quickly
3. The vast majority of content (10,000+ docs pages, aliases, and attachments) now has
   accurate git-based timestamps, providing significant time and bandwidth savings
"""

import os
import re
import subprocess
import sys
from datetime import datetime
from pathlib import Path

CONTENT_DIR = "content/en/docs"
STATIC_DIR = "static"
PUBLIC_DIR = "public"


def extract_urls_from_frontmatter(md_file):
    """
    Extract the url field and aliases from YAML front matter.
    Returns tuple of (url, [aliases]) where url may be None and aliases is a list (possibly empty).
    """
    try:
        with open(md_file, 'r', encoding='utf-8') as f:
            content = f.read()

        # Match YAML front matter between --- markers
        match = re.search(r'^---\s*\n(.*?)\n---\s*\n', content, re.DOTALL | re.MULTILINE)
        if not match:
            return None, []

        frontmatter = match.group(1)

        # Extract url field (handles url: /path/, url: "/path/", url: '/path/')
        url = None
        url_match = re.search(r'^url:\s*["\']?([^"\']+)["\']?\s*$', frontmatter, re.MULTILINE)
        if url_match:
            url = url_match.group(1).strip()

        # Extract aliases (handles both single-line and multi-line YAML arrays)
        aliases = []

        # Try multi-line format first:
        # aliases:
        #     - /path1/
        #     - /path2/
        alias_section = re.search(r'^aliases:\s*\n((?:[ \t]+-[ \t]+.+\n?)+)', frontmatter, re.MULTILINE)
        if alias_section:
            alias_lines = alias_section.group(1)
            alias_matches = re.findall(r'-\s+["\']?([^"\']+)["\']?', alias_lines)
            aliases.extend([a.strip() for a in alias_matches])
        else:
            # Try single-line format: aliases: [/path1/, /path2/]
            alias_single = re.search(r'^aliases:\s*\[([^\]]+)\]', frontmatter, re.MULTILINE)
            if alias_single:
                alias_list = alias_single.group(1)
                alias_matches = re.findall(r'["\']?([^"\']+)["\']?', alias_list.split(','))
                aliases.extend([a.strip() for a in alias_matches if a.strip()])

        return url, aliases
    except Exception as e:
        print(f"ERROR: Failed to read front matter from {md_file}: {e}", file=sys.stderr)
        return None, []


def get_git_modified_dates_batch(file_paths):
    """
    Get git last modified dates for multiple files using xargs + git log.
    Returns dict mapping file path to datetime.
    This is much faster than calling git log for each file individually.
    """
    dates = {}

    if not file_paths:
        return dates

    print(f"Getting git dates for {len(file_paths)} files using batch processing...")

    # Create a temporary file with all the file paths
    import tempfile
    with tempfile.NamedTemporaryFile(mode='w', delete=False, suffix='.txt') as f:
        temp_file = f.name
        for path in file_paths:
            f.write(f"{path}\n")

    try:
        # Use xargs to batch process git log commands
        # This processes multiple files but doesn't overwhelm the system
        if sys.platform == 'win32':
            # Windows: use a simple loop with batching
            file_list = list(file_paths)
            BATCH_SIZE = 50  # Small batches for Windows

            for i in range(0, len(file_list), BATCH_SIZE):
                batch = file_list[i:i+BATCH_SIZE]
                if i % 500 == 0 and i > 0:
                    print(f"  Processed {i}/{len(file_list)} files...")

                for file_path in batch:
                    try:
                        result = subprocess.run(
                            ['git', 'log', '-1', '--format=%ai', '--', str(file_path)],
                            capture_output=True,
                            text=True,
                            timeout=2
                        )
                        date_str = result.stdout.strip()
                        if date_str:
                            git_date = datetime.strptime(date_str[:19], '%Y-%m-%d %H:%M:%S')
                            # Store with both path formats
                            dates[str(file_path)] = git_date
                            dates[str(file_path).replace('\\', '/')] = git_date
                    except:
                        pass
        else:
            # Unix: use xargs for better performance
            cmd = f'cat {temp_file} | xargs -P 4 -I {{}} git log -1 --format="%ai|{{}}" -- {{}}'
            result = subprocess.run(cmd, shell=True, capture_output=True, text=True, timeout=120)

            for line in result.stdout.strip().split('\n'):
                if '|' in line:
                    date_part, file_part = line.split('|', 1)
                    try:
                        git_date = datetime.strptime(date_part.strip()[:19], '%Y-%m-%d %H:%M:%S')
                        dates[file_part] = git_date
                    except:
                        pass

        print(f"Retrieved git dates for {len(dates)//2 if sys.platform == 'win32' else len(dates)} files")
        return dates

    finally:
        # Clean up temp file
        try:
            os.unlink(temp_file)
        except:
            pass


def get_git_modified_date(md_file):
    """
    Get the git last modified date for a single file.
    Returns None if git history is not available.
    """
    try:
        result = subprocess.run(
            ['git', 'log', '-1', '--format=%ai', '--', str(md_file)],
            capture_output=True,
            text=True,
            check=True
        )
        date_str = result.stdout.strip()
        if date_str:
            # Parse git date format: "2024-01-15 10:30:45 +0100"
            # Convert to datetime for touch command
            return datetime.strptime(date_str[:19], '%Y-%m-%d %H:%M:%S')
        return None
    except subprocess.CalledProcessError:
        return None
    except Exception as e:
        print(f"ERROR: Failed to get git date for {md_file}: {e}", file=sys.stderr)
        return None


def update_file_timestamp(file_path, git_date):
    """
    Update the modification time of a file to match the git date.
    """
    try:
        timestamp = git_date.timestamp()
        os.utime(file_path, (timestamp, timestamp))
        return True
    except Exception as e:
        print(f"ERROR: Failed to update timestamp for {file_path}: {e}", file=sys.stderr)
        return False


def sync_static_files(static_path, public_path):
    """
    Sync timestamps for static files from /static to /public.
    Hugo copies static files directly, so the path structure is preserved.
    Returns tuple of (count, skipped, errors).
    """
    count = 0
    skipped = 0
    errors = 0

    if not static_path.exists():
        print(f"WARNING: Static directory not found: {static_path}", file=sys.stderr)
        return count, skipped, errors

    print("Syncing static file timestamps...")

    # Find all files in static directory
    for static_file in static_path.rglob("*"):
        if not static_file.is_file():
            continue

        # Get git last modified date
        git_date = get_git_modified_date(static_file)

        if not git_date:
            skipped += 1
            continue

        # Calculate corresponding file in public directory
        # static/attachments/foo.png -> public/attachments/foo.png
        relative_path = static_file.relative_to(static_path)
        public_file = public_path / relative_path

        if public_file.exists():
            if update_file_timestamp(public_file, git_date):
                count += 1
        else:
            skipped += 1

    return count, skipped, errors


def main():
    print("Syncing file timestamps with git modification dates...")

    html_count = 0
    html_skipped = 0
    html_errors = 0

    content_path = Path(CONTENT_DIR)
    static_path = Path(STATIC_DIR)
    public_path = Path(PUBLIC_DIR)

    if not content_path.exists():
        print(f"ERROR: Content directory not found: {CONTENT_DIR}", file=sys.stderr)
        sys.exit(1)

    if not public_path.exists():
        print(f"ERROR: Public directory not found: {PUBLIC_DIR}", file=sys.stderr)
        sys.exit(1)

    # Process markdown files -> HTML files (including aliases)
    print("Syncing HTML file timestamps...")
    print("[TRACE] Step 1: Collecting markdown files...")
    md_files = list(content_path.rglob("*.md"))
    print(f"[TRACE] Found {len(md_files)} markdown files")

    # Get git dates for all files in one batch operation (much faster!)
    print("[TRACE] Step 2: Getting git modification dates (this may take a moment)...")
    git_dates = get_git_modified_dates_batch(md_files)
    print(f"[TRACE] Retrieved {len(git_dates)} git dates")

    print(f"[TRACE] Step 3: Processing {len(md_files)} markdown files...")
    for file_num, md_file in enumerate(md_files):
        if file_num % 100 == 0:
            print(f"[TRACE] Processing file {file_num}/{len(md_files)}: {md_file.name}")
        # Extract URL and aliases from front matter
        url, aliases = extract_urls_from_frontmatter(md_file)

        if not url:
            print(f"ERROR: No url: field found in front matter: {md_file}", file=sys.stderr)
            html_errors += 1
            continue

        # Get git last modified date from batch results
        md_file_str = str(md_file).replace('\\', '/')  # Normalize path
        git_date = git_dates.get(md_file_str) or git_dates.get(str(md_file))

        if not git_date:
            html_skipped += 1
            continue

        # Collect all URLs to process (main URL + aliases)
        all_urls = [url] + aliases

        # Process each URL (main page and alias pages)
        for page_url in all_urls:
            # Remove leading and trailing slashes from URL
            url_clean = page_url.strip('/')

            # Find corresponding HTML file
            html_file = public_path / url_clean / "index.html"

            if html_file.exists():
                if update_file_timestamp(html_file, git_date):
                    html_count += 1
            else:
                html_skipped += 1

    # Process static files
    static_count, static_skipped, static_errors = sync_static_files(static_path, public_path)

    # Report totals
    total_count = html_count + static_count
    total_skipped = html_skipped + static_skipped
    total_errors = html_errors + static_errors

    print(f"\nTimestamp sync complete:")
    print(f"  HTML files: {html_count} updated, {html_skipped} skipped, {html_errors} errors")
    print(f"  Static files: {static_count} updated, {static_skipped} skipped, {static_errors} errors")
    print(f"  Total: {total_count} updated, {total_skipped} skipped, {total_errors} errors")

    # Exit with error code if there were errors (but still processed all files)
    if total_errors > 0:
        sys.exit(1)


if __name__ == "__main__":
    main()
